#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Appstore Ratings & Reviews Analysis                                                 #
# Version    : 0.1.19                                                                              #
# Python     : 3.10.11                                                                             #
# Filename   : /config/persistence.yml                                                             #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/appstore                                           #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 12:01:04 pm                                                #
# Modified   : Sunday August 27th 2023 05:50:08 am                                                 #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #


# ------------------------------------------------------------------------------------------------ #
#                                         PERSISTENCE                                              #
# ------------------------------------------------------------------------------------------------ #
database:
  name:
    prod: appstore
    test: appstore_test
  backup:
    prod: data/backup/database
    test: tests/data/backup/database

file:
  archive:
    prod: data/backup/archive
    test: tests/data/backup/archive
  staging:
    prod: data/backup/archive/staging
    test: tests/data/backup/archive/staging
  datasets:
    prod: data/backup/datasets
    test: tests/data/datasets

cloud:
  aws_bucket:
    prod: appstore-dataset
    test: appstore-tests