#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Appstore Ratings & Reviews Analysis                                                 #
# Version    : 0.1.19                                                                              #
# Python     : 3.10.11                                                                             #
# Filename   : /config/persistence.yml                                                             #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/appstore                                           #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 12:01:04 pm                                                #
# Modified   : Tuesday August 29th 2023 03:44:02 am                                                #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #


# ------------------------------------------------------------------------------------------------ #
#                                         PERSISTENCE                                              #
# ------------------------------------------------------------------------------------------------ #
database:
  name:
    prod: appstore
    raw:  appstore_raw
    test: appstore_test
  backup:
    prod: data/prod/database
    raw: data/raw/database
    test: tests/data/database

file:
  archive:
    prod: data/prod/archive
    raw: data/raw/archive
    test: tests/data/archive
  staging:
    prod: data/prod/archive/staging
    raw: data/raw/archive/staging
    test: tests/data/archive/staging
  datasets:
    prod: data/prod/datasets
    raw: data/raw/datasets
    test: tests/data/datasets

cloud:
  aws_bucket:
    prod: appstore-final
    raw: appstore_raw
    test: appstore-tests