#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Appstore Ratings & Reviews Analysis                                                 #
# Version    : 0.1.19                                                                              #
# Python     : 3.10.11                                                                             #
# Filename   : /config/persistence.yml                                                             #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/appstore                                           #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 12:01:04 pm                                                #
# Modified   : Thursday August 24th 2023 04:21:42 am                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #


# ------------------------------------------------------------------------------------------------ #
#                                       PERSISTENCE                                                #
# ------------------------------------------------------------------------------------------------ #
database:
  appstore:
    name: appstore

# ------------------------------------------------------------------------------------------------ #
#                                      DATA MANAGER                                                #
# ------------------------------------------------------------------------------------------------ #
dm:
  backup:
    database:
      scripts:
        full: scripts/database/management/backup_full.sh
        incremental: scripts/database/management/backup_inc.sh
      local: data/backup/database
    datasets:
      appdata:
        name: appdata
        location: data/export/appdata
        by_category: False
        fileformat: ".csv"
        sep: ","
      ratings:
        name: ratings
        location: data/export/rating
        by_category: False
        fileformat: ".csv"
        sep: ","
      reviews:
        name: reviews
        location: data/backup/datasets/review
        by_category: True
        fileformat: ".tsv"
        sep: "\t"
    package:
      name: appstore
      location: data/backup/package
      fileformat: ".tar.gz"
  upload:
    aws:
      bucket: appstore-voc
  versioning:
    location: data/backup/version.db


