#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Enter Project Name in Workspace Settings                                            #
# Version    : 0.1.19                                                                              #
# Python     : 3.10.11                                                                             #
# Filename   : /config/web.yml                                                                     #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : Enter URL in Workspace Settings                                                     #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 12:00:43 pm                                                #
# Modified   : Wednesday July 26th 2023 07:48:18 pm                                                #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                        SERVICE CONFIG                                            #
# ------------------------------------------------------------------------------------------------ #
web:
  session:
    retry:                    # Request module TimeOut HTTP Adapter Config
      total_retries: 5
      backoff_factor: 2
      status_forcelist:
      - 104
      - 429
      - 500
      - 502
      - 503
      - 504
      allowed_methods:
      - HEAD
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - TRACE
      raise_on_redirect: True
      raise_on_status: True

    timeout: 30

    session_retries: 3        # An external retry loop in addition to the request retry
    throttle:
      start_delay: 3
      min_delay: 1
      max_delay: 10
      lambda_factor: 0.5
      backoff_factor: 2
      verbose: 100

  async_session:
    concurrency: 10
    timeout: 30
    retries: 5
    athrottle:
      burnin_period: 25
      burnin_reset: 1000
      burnin_rate: 5
      burnin_threshold_factor: 2
      rolling_window_size: 25
      cooldown_factor: 2
      cooldown_phase: 10
      tolerance: 0.8
      rate: 5
      verbose: 100


